
import { Product, Discount } from './types';

export const WILAYAS = [
  "01 - Adrar", "02 - Chlef", "03 - Laghouat", "04 - Oum El Bouaghi", "05 - Batna", 
  "06 - Bejaia", "07 - Biskra", "08 - Bechar", "09 - Blida", "10 - Bouira", 
  "11 - Tamanrasset", "12 - Tebessa", "13 - Tlemcen", "14 - Tiaret", "15 - Tizi Ouzou", 
  "16 - Alger", "17 - Djelfa", "18 - Jijel", "19 - Setif", "20 - Saida", 
  "21 - Skikda", "22 - Sidi Bel Abbes", "23 - Annaba", "24 - Guelma", "25 - Constantine", 
  "26 - Medea", "27 - Mostaganem", "28 - M'Sila", "29 - Mascara", "30 - Ouargla", 
  "31 - Oran", "32 - El Bayadh", "33 - Illizi", "34 - Bordj Bou Arreridj", "35 - Boumerdes", 
  "36 - El Tarf", "37 - Tindouf", "38 - Tissemsilt", "39 - El Oued", "40 - Khenchela", 
  "41 - Souk Ahras", "42 - Tipaza", "43 - Mila", "44 - Ain Defla", "45 - Naama", 
  "46 - Ain Temouchent", "47 - Ghardaia", "48 - Relizane", "49 - El M'Ghair", "50 - El Menia", 
  "51 - Ouled Djellal", "52 - Bordj Baji Mokhtar", "53 - Beni Abbes", "54 - Timimoun", 
  "55 - Touggourt", "56 - Djanet", "57 - In Salah", "58 - In Guezzam"
];

export const DISCOUNT_CODES: Discount[] = [
  { id: 1, code: 'SAVE10', discount_value: 10, discount_type: 'percentage', percentage: 10, description: '10% off your entire order', is_active: true },
  { id: 2, code: 'WELCOME20', discount_value: 20, discount_type: 'percentage', percentage: 20, description: 'New customer special: 20% off', is_active: true },
  { id: 3, code: 'SUPREME', discount_value: 30, discount_type: 'percentage', percentage: 30, description: 'Flash sale: 30% off premium items', is_active: true }
];

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Samsung Galaxy A51 Ultra',
    slug: 'samsung-galaxy-a51-ultra',
    description: 'Pristine condition, 128GB storage with expanded RAM capabilities and a stunning 6.5-inch Super AMOLED display for immersive viewing.',
    price: 599.99,
    category_id: 1,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&h=600&fit=crop',
    rating: 4.8,
    reviews_count: 120,
    stock_quantity: 15,
    low_stock_threshold: 5,
    sku: 'SAM-A51-ULT',
    is_featured: true,
    is_active: true,
    stockStatus: 'In Stock',
    isNew: true
  },
  {
    id: 2,
    name: 'Smart Watch Pro Max',
    slug: 'smart-watch-pro-max',
    description: 'Advanced health tracking, heart rate monitoring, and GPS integration. Features a sleek titanium frame and sapphire glass.',
    price: 349.00,
    category_id: 1,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&h=600&fit=crop',
    rating: 4.6,
    reviews_count: 85,
    stock_quantity: 20,
    low_stock_threshold: 5,
    sku: 'WATCH-PRO-MAX',
    is_featured: false,
    is_active: true,
    stockStatus: 'In Stock'
  },
  {
    id: 3,
    name: 'Premium Audio X1',
    slug: 'premium-audio-x1',
    description: 'Active noise cancellation with studio-grade sound performance. Designed for audiophiles who demand the highest precision.',
    price: 299.99,
    category_id: 1,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=600&fit=crop',
    rating: 4.9,
    reviews_count: 210,
    stock_quantity: 5,
    low_stock_threshold: 2,
    sku: 'AUDIO-X1',
    is_featured: true,
    is_active: true,
    stockStatus: 'In Stock',
    isNew: true
  },
  {
    id: 4,
    name: 'Minimalist Coffee Brew',
    slug: 'minimalist-coffee-brew',
    description: 'Industrial design meets precision brewing for the perfect morning. Ceramic body with double-wall insulation.',
    price: 189.50,
    category_id: 2,
    category: 'Home',
    image: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=600&h=600&fit=crop',
    rating: 4.5,
    reviews_count: 45,
    stock_quantity: 12,
    low_stock_threshold: 3,
    sku: 'COFFEE-MIN',
    is_featured: false,
    is_active: true,
    stockStatus: 'In Stock'
  },
  {
    id: 5,
    name: 'Urban Leather Backpack',
    slug: 'urban-leather-backpack',
    description: 'Handcrafted full-grain leather designed for modern commuters. Multiple compartments for laptops and accessories.',
    price: 145.00,
    category_id: 3,
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&h=600&fit=crop',
    rating: 4.7,
    reviews_count: 67,
    stock_quantity: 8,
    low_stock_threshold: 2,
    sku: 'BACKPACK-URB',
    is_featured: false,
    is_active: true,
    stockStatus: 'In Stock'
  },
  {
    id: 6,
    name: 'Elite Yoga Performance Mat',
    slug: 'elite-yoga-mat',
    description: 'Anti-slip texture with high-density cushioning for intense sessions. Eco-friendly natural rubber material.',
    price: 65.00,
    category_id: 4,
    category: 'Sports',
    image: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=600&h=600&fit=crop',
    rating: 4.8,
    reviews_count: 142,
    stock_quantity: 2,
    low_stock_threshold: 5,
    sku: 'YOGA-ELITE',
    is_featured: false,
    is_active: true,
    stockStatus: 'Low Stock'
  },
  {
    id: 7,
    name: 'Nordic LED Desk Sphere',
    slug: 'nordic-led-sphere',
    description: 'Dimmable smart lighting with customizable color temperatures. App-controlled and voice-compatible.',
    price: 89.99,
    category_id: 2,
    category: 'Home',
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&h=600&fit=crop',
    rating: 4.4,
    reviews_count: 31,
    stock_quantity: 25,
    low_stock_threshold: 5,
    sku: 'LED-NORDIC',
    is_featured: false,
    is_active: true,
    stockStatus: 'In Stock'
  },
  {
    id: 8,
    name: 'AeroStrike Running Shoes',
    slug: 'aerostrike-running',
    description: 'Lightweight carbon-plate technology for explosive speed. Breathable mesh upper with superior traction.',
    price: 175.00,
    category_id: 4,
    category: 'Sports',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop',
    rating: 4.6,
    reviews_count: 89,
    stock_quantity: 0,
    low_stock_threshold: 5,
    sku: 'AERO-RUN',
    is_featured: true,
    is_active: true,
    stockStatus: 'Out of Stock'
  }
];
